name: Backend CI

on:
  push:
    branches:
      - dev

# Définition des jobs
jobs:
  test:
    # Utilisation de l'image PHP pour exécuter les tests
    docker:
      - image: php:8.2-cli
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

      - name: Back
        run: cd ./Back

      # Installation de Composer
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            php -r "unlink('composer-setup.php');"
      # Installation des dépendances du projet
      - run:
          name: Install dependencies
          command: composer install
      # Exécution des tests PHPUnit
      - run:
          name: Run PHPUnit tests
          command: vendor/bin/phpunit

