name: Docker Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Localisation
      run: ls

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Run Tests
      run: docker-compose -f docker-compose.yml exec front npm test

    - name: Stop Docker Compose
      run: docker-compose -f docker-compose.yml down
