name: Docker Build and Test

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Test Front-end Docker Image
      run: |
        docker-compose -f docker-compose.yml build front
        docker-compose -f docker-compose.yml run front npm test

    - name: Build and Test Back-end Docker Image
      run: |
        docker-compose -f docker-compose.yml build back
        docker-compose -f docker-compose.yml run back npm test
