name: Docker Build and Test

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    
    - name: Localisation
      run: ls


    - name: Build and Test Front-end Docker Image
      run: |
        cd Front
        docker build -t front-app .

    - name: Build and Test Back-end Docker Image
      run: |
        cd Back
        docker build -t back-app .
